package com.example.travelista;

import androidx.appcompat.app.AppCompatActivity;

import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.widget.Button;
import android.widget.ImageView;
import android.widget.TextView;
import android.widget.Toast;

import com.google.android.material.textfield.TextInputEditText;
import com.google.firebase.auth.FirebaseAuth;
import com.google.firebase.auth.FirebaseUser;
import com.google.firebase.database.DataSnapshot;
import com.google.firebase.database.DatabaseError;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;
import com.google.firebase.database.ValueEventListener;

public class AddTrip extends AppCompatActivity {

    ImageView btnBack;
    TextView pageName;
    TextInputEditText edtTripName, edtDestination, edtStartDate, edtEndDate, edtTripDescription;

    Button btnSaveTrip;

    DatabaseReference databaseReference = FirebaseDatabase.getInstance().getReferenceFromUrl("https://useful-maxim-382603-default-rtdb.firebaseio.com/");

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_add_trip);

        pageName = findViewById(R.id.pageName);
        pageName.setText("Add Trip");

        // Get User Information
        FirebaseAuth mAuth = FirebaseAuth.getInstance();
        FirebaseUser user = mAuth.getCurrentUser();
        String uID = user.getUid();
        DatabaseReference userRef = databaseReference.child("userID").child(uID);

        edtTripName = findViewById(R.id.edtTripName);
        edtDestination = findViewById(R.id.edtDestination);
        edtStartDate = findViewById(R.id.edtStartDate);
        edtEndDate = findViewById(R.id.edtEndDate);
        edtTripDescription = findViewById(R.id.edtTripDescription);

        btnSaveTrip = findViewById(R.id.btnSaveTrip);
        btnSaveTrip.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {

                String tripName = edtTripName.getText().toString();
                String tripDestination = edtDestination.getText().toString();
                String tripStartDate = edtStartDate.getText().toString();
                String tripEndDate = edtEndDate.getText().toString();
                String tripDescription = edtTripDescription.getText().toString();

                databaseReference.child("userID").child(uID).child("tripList");

                userRef.addListenerForSingleValueEvent(new ValueEventListener() {
                    @Override
                    public void onDataChange(DataSnapshot dataSnapshot) {

                        // Generate a reference to the tripList child node
                        DatabaseReference tripListRef = databaseReference.child("userID").child(uID).child("tripList");

                        // Push a new child node with trip details
                        DatabaseReference newTripRef = tripListRef.push();
                        newTripRef.child("tripName").setValue(tripName);
                        newTripRef.child("tripDestination").setValue(tripDestination);
                        newTripRef.child("tripStartDate").setValue(tripStartDate);
                        newTripRef.child("tripEndDate").setValue(tripEndDate);
                        newTripRef.child("tripDescription").setValue(tripDescription);

                        // Get the unique ID generated by push() by accessing its key
                        String tripID = newTripRef.getKey();

                        Toast.makeText(AddTrip.this, "Trip is successfully added!", Toast.LENGTH_SHORT).show();
                    }

                    @Override
                    public void onCancelled(DatabaseError error) {
                        Toast.makeText(AddTrip.this, "Error.", Toast.LENGTH_SHORT).show();
                    }
                });

                // Open Trip Details
                Intent intent = new Intent(AddTrip.this, TripDetails.class);
                startActivity(intent);
                finish();
            }
        });







        // Back Button
        btnBack = findViewById(R.id.btnBack);
        btnBack.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                finish();
            }
        });
    }
}